import * as THREE from 'three';
import { createScene } from './render/scene';
import { createPost } from './render/post';
import { buildRoads } from './render/roads';
import { buildBuildings } from './render/buildings';
import { buildLandmarks } from './render/landmarks';
import { buildTerrain, buildGround } from './render/terrain';
import { makeGround, type Dem } from './world/terrain';
import { loadCity, nearestEdge, pointOnEdge } from './world/city';
import { project, SPAWN, type CityData } from './world/osm';
import { routeLength } from './world/routing';
import { rasterize, boxesAround } from './vehicle/occupancy';
import { stepCar, type CarState } from './vehicle/carPhysics';
import { resolveCar } from './vehicle/collision';
import { createPlayerCar } from './vehicle/playerCar';
import { readCarInput, consumeKey } from './input';
import { createChaseCamera } from './camera/chaseCamera';
import { createQuest, stepQuest, questTarget, questPois, type Quest } from './quest/quest';
import { createHud } from './ui/hud';
import { createMarkers } from './quest/markers';
import { spawnTraffic, stepTraffic, trafficCircles } from './traffic/traffic';
import { createTrafficRenderer } from './traffic/trafficRenderer';

const canvas = document.getElementById('game') as HTMLCanvasElement;
const ctx = createScene(canvas);
const post = createPost(ctx);
const [data, dem]: [CityData, Dem] = await Promise.all([fetch('/purwokerto.json').then((r) => r.json()), fetch('/dem.json').then((r) => r.json())]);
const city = loadCity(data);
const ground = makeGround(dem);
ctx.scene.add(buildGround(ground, data.areas ?? []), buildTerrain(data, ground), buildRoads(city, ground), buildBuildings(data.buildings, ground), buildLandmarks(data.pois, ground));
const occupancy = rasterize(data.buildings, data.trees);
const player = await createPlayerCar(ctx.scene);
const chase = createChaseCamera(ctx, ground);

const pois = questPois(city, data.pois);
const kitchen = pois.find((p) => p.kind === 'kitchen')!;
const schools = pois.filter((p) => p.kind === 'school');
const routeLen = routeLength(city, [kitchen, ...schools].map((p) => p.stop.node));
const [sx, sz] = project(SPAWN.lat, SPAWN.lon);
const spawnEdge = nearestEdge(city, sx, sz);
const spawn = pointOnEdge(city, spawnEdge.edge, spawnEdge.t);
const resetCar = (): CarState => ({ x: spawn.x, z: spawn.z, heading: spawn.heading, speed: 0 });
let car = resetCar();
const traffic = spawnTraffic(city, 30, Math.random, car);
const trafficView = await createTrafficRenderer(ctx.scene, traffic, ground);
let quest: Quest = createQuest(kitchen, schools, 1, routeLen);
const hud = createHud(city, ground);
const markers = createMarkers(ctx.scene, ground);
document.getElementById('loading')!.remove();

const clock = new THREE.Clock();
ctx.renderer.setAnimationLoop(() => {
  const dt = Math.min(clock.getDelta(), 0.05);
  const input = readCarInput();
  car = stepCar(car, input, dt);
  stepTraffic(city, traffic, [car], dt, Math.random, car);
  car = resolveCar(car, boxesAround(occupancy, car.x, car.z), trafficCircles(traffic));
  trafficView.update(dt);
  player.sync(car, input, dt, ground);
  quest = stepQuest(quest, car, dt);
  if (consumeKey('KeyR') && (quest.phase === 'done' || quest.phase === 'failed')) {
    quest = createQuest(kitchen, schools, quest.phase === 'done' ? quest.round + 1 : 1, routeLen);
    car = resetCar();
    chase.reset();
  }
  markers.update(questTarget(quest), car, clock.elapsedTime);
  hud.update(quest, car);
  chase.update(car, dt);
  post.render();
});
